version: 2
jobs:
  build:
    working_directory: ~/wp
    branches:
      - master
      - develop
    docker:
      - image: docker:17.09.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Save version
          command: echo "${CIRCLE_BRANCH}_${CIRCLE_SHA1:0:7}" > version.txt
      - run:
          name: List current directory directly
          command: ls -lA
      - run:
          name: List current directory
          command: docker run --rm -t -v /root/wp:/app -w /app alpine:latest ls -lA
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=wp -t wp:${CIRCLE_SHA1:0:7} -f Dockerfile .
      - deploy:
          name: Push application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              mkdir -p ~/.docker
              echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"$DOCKER_CREDS\"}}}" > ~/.docker/config.json
              docker push "${DOCKER_IMAGE_REPO}:${CIRCLE_SHA1:0:7}"
              rm -f ~/.docker/config.json
            fi
