version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1.5-browsers
    working_directory: ~/
    steps:
      - checkout
      - run:
          name: Save version
          command: echo "${CIRCLE_SHA1:0:7}" > version.txt
      - run:
          name: env variables
          command: env | sort
  build_docker:
    working_directory: ~/
    docker:
      - image: docker:17.09.0-ce-git
    steps:
      - setup_remote_docker
      - run:
          name: List current directory
          command: ls -lA
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=wp -t wp -f Dockerfile .
