defaults: &defaults
  working_directory: /tmp/workspace

version: 2
jobs:
  build:
    <<: *defaults
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # - run: npm build
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - .
  build_docker:
    <<: *defaults
    docker:
      - image: docker:17.09.0-ce-git
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=wp -t ${DOCKER_IMAGE_REPO}:${CIRCLE_SHA1:0:7} -f Dockerfile .
      - run:
          name: Push application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              mkdir -p ~/.docker
              echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"$DOCKER_CREDS\"}}}" > ~/.docker/config.json
              docker push "${DOCKER_IMAGE_REPO}:${CIRCLE_SHA1:0:9}"
              rm -f ~/.docker/config.json
            fi
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - develop
      - build_docker:
          filters:
            branches:
              only:
                - master
                - develop
          requires:
            - build
